# Generated by Django 4.1.4 on 2023-01-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=20)),
                ('P_Name', models.CharField(max_length=25)),
                ('P_No', models.CharField(max_length=20)),
                ('P_Description', models.CharField(max_length=200)),
                ('P_Price', models.CharField(max_length=25)),
                ('P_CurrentStock', models.CharField(max_length=25)),
                ('p_photo', models.ImageField(upload_to='product/')),
                ('seller_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
